language: node_js
node_js:
- "4.1"
- "0.10"
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
env:
  global:  
before_install:
- echo "Before install stage"
- node -v
- npm -v
install:
- echo "Install stage"
- npm install
- export PATH=$(npm bin):$PATH
before_script:
- echo "Before script stage"
script:
- echo "Script stage"
- npm test
- mocha .\test\main.test.js
after_success:
- echo "After success stage"
after_failure:
- echo "After failure stage"
after_script:
- echo "After script stage"
